services:

  api:
    build: ./app
    restart: always
    env_file: ./app/.env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - 8000:8000
    depends_on:
      worker:
        condition: service_healthy
    profiles: [main, app]

  worker:
    build: ./worker
    restart: always
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "app.main", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: [main, app]

  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: [main, app]

  flower:
    build: ./worker
    restart: always
    command: ["celery", "-A", "app.main", "flower", "--persistent=True"]
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - 5555:5555
    volumes:
      - ./worker/app:/worker/app
    depends_on:
      worker:
        condition: service_healthy
    profiles: [main, ui]

volumes:
  redis_data: