name: E2E Testing of the App and Worker Applications

on:
  push:
    branches: [main]

defaults:
 run:
  working-directory: ./app

jobs:
  checks:
    name: Test Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.7.13"

      - name: Install dependencies
        run: uv sync --locked --all-extras --group test

      - name: Create global configuration file
        run: cp ../.env.example ../.env

      - name: Create configuration file for the main application
        run: cp .env.example .env

      - name: Create configuration file for the worker application
        run: cp ../worker/.env.example ../worker/.env

      - name: Run all Services (excluding flower)
        run: docker compose  -f ../docker-compose.yml --profile app up -d

      - name: Run E2E Tests
        run: |
          until curl -s -f http://localhost:8000/health > /dev/null; do sleep 1; done && \
          uv run pytest

      - name: Terminate all Services
        run: docker compose -f ../docker-compose.yml --profile app down -v
