name: End-to-End Testing of App and Worker

on:
  push:
    branches: [main]

jobs:
  checks:
    name: Test Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Check Docker Compose Version
        run: docker compose version

      # - name: Install App Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r app/requirements.test.txt

      # - name: Start Services
      #   run: docker compose --profile app up -d

      # - name: Run E2E Tests
      #   run: |
      #     until curl -s -f http://localhost:8000/health > /dev/null; do sleep 1; done && \
      #     E2E_MODE_DISABLED=0 pytest -vsx app/tests

      # - name: Stop Services
      #   run: docker compose --profile app down -v
